Adiciona diretório de municípios.
base-dos-dados/bases pull request #48
Opened 2020-09-29 21:54 UTC by rdahis

2020-09-29 22:04 UTC, JoaoCarabetta requested changes

2020-09-29 22:04 UTC, JoaoCarabetta commented on bases/br_suporte/diretorio_municipios/table_config.yaml
> +data_update_frequency: recorrente # REQUIRED
Aqui tem que usar alguma das tags acima. Temos que melhorar os comentários para deixar isso explícito. Também vou adicionar uma opção 'recorrente'

2020-09-29 22:04 UTC, JoaoCarabetta commented on bases/br_suporte/diretorio_municipios/table_config.yaml
> +last_updated: 29/09/2020 # AUTO GENERATED
Vamos usar 

'YYYY-MM-DD'

Vou automatizar isso em breve

2020-09-29 22:04 UTC, JoaoCarabetta commented on bases/br_suporte/diretorio_municipios/publish.sql
> +SAFE_CAST(existia_1991 AS BOOL) existia_1991,
Tudo que tem BOOL como tipo ficou nulo na tabela final.

Talvez seja melhor deixar como NUMERIC mesmo

![image](https://user-images.githubusercontent.com/19963732/94621345-782cb080-0286-11eb-821a-b612155b4500.png)

2020-09-29 22:04 UTC, JoaoCarabetta commented on bases/br_suporte/diretorio_municipios/table_config.yaml
>      code_url: <code-url-that-generated-table> # REQUIRED
Faltou o código

2020-09-29 22:06 UTC, JoaoCarabetta commented on bases/br_suporte/diretorio_municipios/table_config.yaml
>      code_url: <code-url-that-generated-table> # REQUIRED
Acho que é só colocar o código de STATA na pasta code.

Vou escrever nos comentários como colocar o caminho para uma pasta que ainda não existe no master

2020-09-29 22:25 UTC, rdahis commented on bases/br_suporte/diretorio_municipios/table_config.yaml
> +data_update_frequency: recorrente # REQUIRED
Ótimo, eu tinha marcado isso em #51.

2020-09-29 22:28 UTC, rdahis commented on bases/br_suporte/diretorio_municipios/table_config.yaml
>      code_url: <code-url-that-generated-table> # REQUIRED
Nesse caso não tem código mesmo porque foi feito na mão. Único código foi para join diferentes colunas.

2020-09-30 00:55 UTC, JoaoCarabetta commented on bases/br_suporte/diretorio_municipios/table_config.yaml
>      code_url: <code-url-that-generated-table> # REQUIRED
Harcode. hahahahah

2020-09-30 15:49 UTC, merged